### ISSUE TITLE
The default port 80 in `kellnr.local.port` cannot be bound in confined clusters

### ISSUE THREAD

**Issue by Teebor-Choka** [kellnr/helm#13]
The `80` port cannot be bound in confined clusters, the default value should reflect the one configured in the docker image, e.g. `8000`.

**Comment by andreyddk** [comment]
Fast solution.

`helm show values kellnr/kellnr > values.yaml
`
```
kellnr:
  local:
    ip: "0.0.0.0"
    port: 8080

service:
  api:
    type: ClusterIP
    port: 8080
```

`helm upgrade --install kellnr kellnr/kellnr -n kellnr --create-namespace -f values.yaml`
