### ISSUE TITLE
Secret values should not be present in the ConfigMap, but rather a dedicated secret

### ISSUE THREAD

**Issue by Teebor-Choka** [kellnr/helm#14]
Secret values cannot be inserted into the helm chart using a dedicated secret, and are stored upon configuration in the `ConfigMap`.

This is a malpractice and the secrets should ideally be stored in a dedicated `Secret`.

Relevant secret information is, e.g.:
```yaml
kellnr:
  setup:
    adminPwd: "admin"
    adminToken: "Zy9HhJ02RJmg0GCrgLfaCVfU6IwDfhXD"
```
